# Generated by Django 3.2.6 on 2021-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
