# Generated by Django 3.2.6 on 2021-10-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20211007_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='body',
        ),
    ]
