# Generated by Django 3.2.6 on 2021-10-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_rename_description_event_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='null', upload_to='static/images/'),
        ),
    ]
