# Generated by Django 3.2.6 on 2021-10-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_rename_event_image_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='null', upload_to='../static/images/'),
        ),
    ]
