# Generated by Django 3.2.6 on 2021-10-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
