# Generated by Django 3.2.6 on 2021-10-20 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_holder', models.CharField(max_length=55)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.event')),
            ],
        ),
    ]
