# Generated by Django 3.2.6 on 2021-10-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_auto_20211019_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_email',
            field=models.TextField(max_length=55),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_first_name',
            field=models.TextField(max_length=55),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_last_name',
            field=models.TextField(max_length=55),
        ),
    ]
