# Generated by Django 3.2.6 on 2021-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_auto_20211019_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_last_name',
            field=models.TextField(),
        ),
    ]
