# Generated by Django 3.2.6 on 2021-10-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_auto_20211021_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_email',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_last_name',
            field=models.CharField(max_length=25),
        ),
    ]
