# Generated by Django 3.2.6 on 2021-10-27 02:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_auto_20211021_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_email',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_holder_last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
