# Generated by Django 3.2.6 on 2021-10-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_auto_20211026_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_attendee',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendee',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
