# Generated by Django 3.2.6 on 2021-10-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0019_auto_20211028_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='current_attendee',
            new_name='current_attendee_count',
        ),
    ]
